### ISSUE TITLE
Incorrect label tau when plotting discrete systems with draw_all_lds

### ISSUE THREAD

**Issue by broncio123** [champsproject/ldds#43]
![image](https://user-images.githubusercontent.com/17453074/104489856-06c00600-55c8-11eb-805c-aa01d66a1ad8.png)

**Comment by vkrajnak** [comment]
Indeed in a discrete system time, i.e. number of iteration, is usually not denoted as tau. Since `draw_all_lds` is called the notebook, using the plot handle to add a title from the notebook is not feasible. I can suggest removing it, or much rather leave it as is and address this discrepancy in the documentation. In the end, it's not that bad, is it?

**Comment by vkrajnak** [comment]
Discussed, agreed to leave it as is

**Comment by vkrajnak** [comment]
#49
